### ISSUE TITLE
"metadata_giotto.csv" is missing.

### ISSUE THREAD

**Issue by daqiancode** [Lotfollahi-lab/nichecompass-reproducibility#8]
Where is the "metadata_giotto.csv" in data_preparation.ipynb in nanostring_cosmx_human_nsclc dataset?
I can't find "metadata_giotto.csv" in https://nanostring.com/products/cosmx-spatial-molecular-imager/ffpe-dataset/nsclc-ffpe-dataset/.
Thanks

**Comment by sebastianbirk** [comment]
Hi,
You can find the file in our publicly accessible [GDrive](https://drive.google.com/drive/folders/17iVRDEyNXXvJVKFBAlug8h3OAXrSVXeL).
